### PR TITLE
Add Zig version (Fixes #16)

### LINKED ISSUE #16: Add version info
Sat 11 Mar 2023 08:43:11 GMT

Would it be possible to add the `zig version` being used?

### PR DESCRIPTION
**Pull request by rprimus**
Sat 11 Mar 2023 09:45:41 GMT

Add Zig version to the sample program.

### CODE REVIEW

**Comment by gsquire** [comment]
Hello, I think this would be a good change to have. Should we add this to the page itself though? If we put it in the sample source code people will just overwrite it.

**Comment by rprimus** [comment]
Sun 12 Mar 2023 18:26:06 GMT

Ideally, yes, but beyond my current html / js capabilities.

Options (to minimise calls to Zig to get the version):
1. Save the version to a file (offline).  Read the file and cache its value.  The version file is regenerated when Zig is updated.
2. Have `js` call `zig version` and use session cookies (or browser storage) to store the value.

Thoughts?

**Comment by gsquire** [comment]
I'm okay with hard coding it in the HTML. We only run a single version so I think that's fine to do.

**Comment by rprimus** [comment]
Sun 12 Mar 2023 19:00:27 GMT

How does this look?

image

**Comment by gsquire** [comment]
LGTM!

**Comment by gsquire** [comment]
Your new patch should be up and running now. Thanks again!

**Comment by rprimus** [comment]
Sun 12 Mar 2023 19:32:52 GMT

Confirmed.  Still thinking about a way to automatically update the heading when a new Zig version is installed.

**Comment by gsquire** [comment]
Sounds good, I think that would be nice to try and automate it so I don't forget in the future when I do upgrade the version in the Dockerfile.

**Pull request merged**
