### PR TITLE
Update Dockerfile: Set version using ARG

### PR DESCRIPTION
**Pull request by rprimus**
Mon 13 Mar 2023 21:07:31 GMT

1. Capture version using `ARG`
2. Create `static/zig-version`

### CODE REVIEW

**Comment by gsquire** [comment]
This is clever, thanks.

**Comment by rprimus** [comment]
Wed 15 Mar 2023 07:44:11 GMT

Has a new container been built / deployed?   The header is showing `v0.10.1` vs `0.10.1`.  I left the `v` off to visually verify that the site was using the new code.  (Also why I'd not removed the `zig-version` file.)

**Comment by gsquire** [comment]
Sorry, I thought maybe the `zig-version` file was leftover from testing. I can deploy a new image here shortly.

**Comment by rprimus** [comment]
Thu 16 Mar 2023 08:21:40 GMT

The new version now appears for me at `zig-play.dev`.
Are you happy with the location of the version information (in the header)?

image

**Pull request merged**
